#version: '3.8'
services:
  db:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    networks:
      - querybot-network
    volumes:
      - ./qdrant_data:/qdrant/storage

networks:
  querybot-network:
    driver: bridge
